"""add anonymous fields to chat_session

Revision ID: 50b8a14bedf3
Revises: c5ca9b6e54c5
Create Date: 2025-11-13 12:03:37.773828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50b8a14bedf3'
down_revision: Union[str, Sequence[str], None] = 'c5ca9b6e54c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_session', sa.Column('is_anonymous', sa.Boolean(), nullable=False))
    op.add_column('chat_session', sa.Column('session_secret_hash', postgresql.BYTEA(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_session', 'session_secret_hash')
    op.drop_column('chat_session', 'is_anonymous')
    # ### end Alembic commands ###
