"""Create chat_session table

Revision ID: c5ca9b6e54c5
Revises: 
Create Date: 2025-11-13 01:38:52.843734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5ca9b6e54c5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('auth_provider', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_user'))
    )
    op.create_index('idx_user_email', 'app_user', ['email'], unique=False)
    op.create_index(op.f('ix_app_user_email'), 'app_user', ['email'], unique=True)
    op.create_table('access_token',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_access_token_user_id_app_user')),
    sa.PrimaryKeyConstraint('token', name=op.f('pk_access_token'))
    )
    op.create_index('idx_access_token_expires', 'access_token', ['expires_at'], unique=False)
    op.create_index('idx_access_token_user', 'access_token', ['user_id'], unique=False)
    op.create_table('chat_session',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_chat_session_user_id_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_session'))
    )
    op.create_index('idx_chat_session_expires', 'chat_session', ['expires_at'], unique=False)
    op.create_index('idx_chat_session_user_updated', 'chat_session', ['user_id', 'updated_at'], unique=False)
    op.create_table('oauth_provider_account',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_oauth_provider_account_user_id_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_provider_account')),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_provider_user')
    )
    op.create_index('idx_oauth_user', 'oauth_provider_account', ['user_id'], unique=False)
    op.create_table('chat_history',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.id'], name=op.f('fk_chat_history_session_id_chat_session')),
    sa.PrimaryKeyConstraint('session_id', name=op.f('pk_chat_history'))
    )
    op.create_index('idx_chat_history_expires', 'chat_history', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_chat_history_expires', table_name='chat_history')
    op.drop_table('chat_history')
    op.drop_index('idx_oauth_user', table_name='oauth_provider_account')
    op.drop_table('oauth_provider_account')
    op.drop_index('idx_chat_session_user_updated', table_name='chat_session')
    op.drop_index('idx_chat_session_expires', table_name='chat_session')
    op.drop_table('chat_session')
    op.drop_index('idx_access_token_user', table_name='access_token')
    op.drop_index('idx_access_token_expires', table_name='access_token')
    op.drop_table('access_token')
    op.drop_index(op.f('ix_app_user_email'), table_name='app_user')
    op.drop_index('idx_user_email', table_name='app_user')
    op.drop_table('app_user')
    # ### end Alembic commands ###
